import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import {
  Search, Filter, Calendar, ArrowRight, AlertCircle, CheckCircle2,
  RefreshCw, Camera,
} from 'lucide-react'
import AppShell from '@/layout/AppShell'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { analysisHistory } from '@/data/mock'

const filters = ['All Reports', 'Rice', 'Tomato', 'Potato', 'Last 30 Days']

const statusMap = {
  critical: { label: 'Critical', variant: 'destructive', icon: AlertCircle },
  resolved: { label: 'Resolved', variant: 'success', icon: CheckCircle2 },
  progress: { label: 'In Progress', variant: 'warning', icon: RefreshCw },
}

export default function HistoryPage() {
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('All Reports')

  const items = useMemo(() => {
    return analysisHistory.filter((item) => {
      const matchQuery =
        !query ||
        item.title.toLowerCase().includes(query.toLowerCase()) ||
        item.summary.toLowerCase().includes(query.toLowerCase())
      const matchFilter =
        filter === 'All Reports' ||
        filter === 'Last 30 Days' ||
        item.crop === filter
      return matchQuery && matchFilter
    })
  }, [query, filter])

  return (
    <AppShell>
      <>
        <main className="py-4 md:py-6 px-8 max-w-7xl mx-auto min-h-screen">
          <div className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-6">
            <div>
              <h1 className="text-3xl md:text-5xl font-bold text-on-surface tracking-tight mb-2">
                Analysis History
              </h1>
              <p className="text-lg text-on-surface-variant max-w-2xl">
                Access and manage all previous crop diagnostic reports generated by AgriSense AI.
              </p>
            </div>
            <div className="flex items-center gap-3">
              <div className="relative">
                <Search
                  size={18}
                  className="absolute left-3 top-1/2 -translate-y-1/2 text-outline"
                />
                <Input
                  className="pl-10 w-full md:w-64 bg-neutral-50"
                  placeholder="Search reports..."
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                />
              </div>
              <Button variant="soft" className="bg-surface-container-high">
                <Filter size={16} /> Filters
              </Button>
            </div>
          </div>

          <div className="flex flex-wrap gap-2 mb-8">
            {filters.map((f) => (
              <button
                key={f}
                type="button"
                onClick={() => setFilter(f)}
                className={`px-4 py-1.5 rounded-full text-[13px] font-semibold transition-all duration-200 ${
                  filter === f
                    ? 'bg-primary text-primary-foreground'
                    : 'bg-surface-container-high text-on-surface-variant hover:bg-outline-variant'
                }`}
              >
                {f}
              </button>
            ))}
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {items.map((item) => {
              const status = statusMap[item.status]
              const StatusIcon = status.icon
              return (
                <div
                  key={item.id}
                  className="group bg-surface border border-outline-variant rounded-2xl overflow-hidden shadow-[0px_4px_20px_rgba(0,0,0,0.04)] hover:shadow-lg hover:-translate-y-1 transition-all duration-300"
                >
                  <div className="relative h-48 overflow-hidden">
                    <img
                      src={item.image}
                      alt={item.title}
                      className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                    />
                    <div className="absolute top-3 right-3">
                      <Badge variant={status.variant}>
                        <StatusIcon size={14} /> {status.label}
                      </Badge>
                    </div>
                  </div>
                  <div className="p-6">
                    <div className="flex justify-between items-start mb-2">
                      <h3 className="text-xl font-semibold text-on-surface">{item.title}</h3>
                      <span className="text-primary font-bold text-xl">{item.confidence}%</span>
                    </div>
                    <div className="flex items-center gap-2 text-on-surface-variant mb-4">
                      <Calendar size={16} />
                      <span className="text-[13px] font-semibold">{item.date}</span>
                    </div>
                    <p className="text-base text-on-surface-variant mb-4 line-clamp-2">
                      {item.summary}
                    </p>
                    <Button
                      className="w-full"
                      variant={item.status === 'critical' ? 'default' : 'outline'}
                      asChild
                    >
                      <Link to="/app/analysis/result">
                        View Full Report <ArrowRight size={16} />
                      </Link>
                    </Button>
                  </div>
                </div>
              )
            })}

            <Link
              to="/app/analysis/new"
              className="flex flex-col items-center justify-center border-2 border-dashed border-outline-variant rounded-2xl p-6 bg-surface-container-lowest hover:bg-primary/5 hover:border-primary transition-all group min-h-[320px]"
            >
              <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center text-primary group-hover:scale-110 transition-transform mb-3">
                <Camera size={32} />
              </div>
              <h3 className="text-xl font-semibold text-on-surface mb-1">New Scan</h3>
              <p className="text-base text-on-surface-variant text-center">
                Capture a photo to start a new crop analysis.
              </p>
            </Link>
          </div>

          <div className="mt-16 flex justify-center items-center gap-2">
            <button
              type="button"
              disabled
              className="p-2 rounded-lg border border-outline-variant opacity-50"
            >
              ‹
            </button>
            {[1, 2, 3].map((n) => (
              <button
                key={n}
                type="button"
                className={`w-10 h-10 rounded-lg text-[13px] font-semibold transition-colors ${
                  n === 1
                    ? 'bg-primary text-primary-foreground'
                    : 'hover:bg-surface-container-high'
                }`}
              >
                {n}
              </button>
            ))}
            <span className="px-2 text-on-surface-variant">...</span>
            <button
              type="button"
              className="w-10 h-10 rounded-lg hover:bg-surface-container-high text-[13px] font-semibold"
            >
              8
            </button>
            <button type="button" className="p-2 rounded-lg border border-outline-variant">
              ›
            </button>
          </div>
        </main>
      </>
    </AppShell>
  )
}
